var a=String.fromCharCode(65);//it will print the value which is in the ASCI value in the above example in asci value 65 its value is A;in asci value 97 there is small a;
console.log(a);
var b=String.fromCharCode(66);
var c=String.fromCharCode(67);
var d=String.fromCharCode(68);
var e=String.fromCharCode(69);
var f=String.fromCharCode(70);
var g=String.fromCharCode(71);
var h=String.fromCharCode(72);
var i=String.fromCharCode(73);
var j=String.fromCharCode(74);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);