var x="hello how are you";
var y=33;
var z=true;
var a=null;
var g=["hello",24,true,4.3,"z",'h'];
var h={name:"waqas",job:"nothing",life:"busy"};
var i;
document.write(x);
document.write("<br>");
document.write(typeof x);
document.write("<br>");
document.write(y);
document.write("<br>");
document.write(typeof y);
document.write("<br>");
document.write(z);
document.write("<br>");
document.write(typeof z);
document.write("<br>");
document.write(a);
document.write("<br>");
document.write(typeof a);
document.write("<br>");
document.write(g);
document.write("<br>");
document.write(typeof g);
document.write("<br>");
document.write(h);
document.write("<br>");
document.write(typeof h);
document.write("<br>");
document.write(i);
document.write("<br>");
document.write(typeof i);